name: Build Pipeline

on:
  push:
    branches:
      - master  # Если вы используете ветку master
  pull_request:
    branches:
      - master  # Если вы используете ветку master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Используем действие для получения кода из репозитория
    - name: Setup .NET
      uses: actions/setup-dotnet@v1  # Установка среды .NET
      with:
        dotnet-version: '6.0.x'  # Укажите версию .NET, которую используете
    - name: Restore dependencies
      run: dotnet restore  # Восстановление зависимостей
    - name: Build
      run: dotnet build --configuration Release --no-restore  # Сборка проекта без восстановления зависимостей
    - name: Run tests
      run: dotnet test --no-restore --verbosity normal  # Запуск тестов
